# Generated by Django 5.0.6 on 2024-06-18 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('result', models.TextField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtest.procedure')),
            ],
        ),
    ]
