# Generated by Django 3.x.x on YYYY-MM-DD HH:MM

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('steps', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
    ),
    migrations.CreateModel(
        name='LabTest',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=100)),
            ('description', models.TextField()),
            ('date_created', models.DateTimeField(auto_now_add=True)),
            ('last_modified', models.DateTimeField(auto_now=True)),
            ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Protocol')),
        ],
    ),
]
